# .github/workflows/generate-tours.yml
name: Split-and-Merge Tours

on:
  push:
    branches: [ main ]
    paths:
      - 'generate_tours.py'
      - 'merge_tours.py'
      - '.github/workflows/generate-tours.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branchIndex: [0, 1]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate branch ${{ matrix.branchIndex }}
        run: |
          python generate_tours.py 100000 ${{ matrix.branchIndex }}

      - name: Upload branch tours
        uses: actions/upload-artifact@v2
        with:
          name: tours-${{ matrix.branchIndex }}
          path: tours-${{ matrix.branchIndex }}.json

  merge:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Download branch 0 tours
        uses: actions/download-artifact@v2
        with:
          name: tours-0
          path: .

      - name: Download branch 1 tours
        uses: actions/download-artifact@v2
        with:
          name: tours-1
          path: .

      - name: Merge into tours.json
        run: python merge_tours.py

      - name: Commit merged file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: regenerate merged tours.json"
          file_pattern: "tours.json"
          branch: main
          author_name: github-actions
          author_email: github-actions@github.com
