# .github/workflows/generate-tours.yml
name: Generate & Merge Tours

on:
  push:
    branches: [ main ]
    paths:
      - 'generate_tours.py'
      - 'merge_tours.py'
      - '.github/workflows/generate-tours.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout so we can commit
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      # 2) Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3) Generate both branches locally
      - name: Generate branch 0 and 1 tours
        run: |
          python generate_tours.py 100000 0
          python generate_tours.py 100000 1

      # 4) Merge into tours.json
      - name: Merge tours
        run: |
          python merge_tours.py

      # 5) Commit & push tours.json back to main
      - name: Commit tours.json
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add tours.json
          git diff --quiet && echo "No changes to tours.json" || git commit -m "chore: regenerate tours.json"
          git push
