name: Update Google Scholar Publications

on:
  schedule:
    - cron: '0 2 * * 1'    # every Monday at 02:00 UTC
  workflow_dispatch:       # manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install scholarly
        run: pip install scholarly

      - name: Scrape Google Scholar
        run: python scripts/update_publications.py

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add publications.json
          git commit -m "Automated update of publications.json"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
